name:                hs-ast
version:             0.1.0.0
github:              "hnefatl/hs-ast"
license:             BSD3
author:              "Keith Collister"
maintainer:          "collisterkeith@gmail.com"
copyright:           "2019 Keith Collister"

extra-source-files:
- README.md

synopsis:            Super simple program to pretty-print the AST of a Haskell 98 source file.

description:         Please see the README on Github at <https://github.com/hnefatl/hs-ast#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall

executables:
  hs-ast:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - haskell-src
    - pretty-simple